[google]
client_id = "220596570262-3ihekoe83p6pn7cqvn2m45aj9u0jqaq1.apps.googleusercontent.com"
client_secret = "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"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
redirect_uri = "https://ptpapp-qjxrob2c9ydjxeroncdq9z.streamlit.app/"
